#!/bin/bash
rm test.out
#arr=( 1 1 1 1 1 1 1 1 1 1 ) 
i=1
variable=1
while [ $i -lt 10 ] ; do
arr[$i]=$variable 
variable=$(echo $variable + $i | bc)
i=$(echo $i + 1 | bc )  
if [ $i -gt 3 ]
then 
echo ${arr[$i-2]}
fi 
done

var2=0
#ar2=$(awk -F, ' {print $(NF-1)}' test.out )

